//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPILab
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GARSupport2020Entities : DbContext
    {
        public GARSupport2020Entities()
            : base("name=GARSupport2020Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Issue> Issue { get; set; }
        public virtual DbSet<Note> Note { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Users_Issue> Users_Issue { get; set; }
    }
}
