//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPILab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Issue()
        {
            this.Comment = new HashSet<Comment>();
            this.Note = new HashSet<Note>();
            this.Users_Issue = new HashSet<Users_Issue>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_client { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> time_stamp { get; set; }
        public string contact_phone { get; set; }
        public string contact_email { get; set; }
        public string classification { get; set; }
        public string status { get; set; }
        public string service_type { get; set; }
        public string name { get; set; }
        public string second_name { get; set; }
        public string first_name { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string second_contact { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Note { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users_Issue> Users_Issue { get; set; }
    }
}
