//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPILab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Issue
    {
        public int id { get; set; }
        public Nullable<int> id_users { get; set; }
        public Nullable<int> id_issue { get; set; }
    
        public virtual Issue Issue { get; set; }
        public virtual Users Users { get; set; }
    }
}
